### ISSUE TITLE
BTreeIndex.Open()

### ISSUE THREAD

**Issue by colinfong** [stanwayl/bruinbase#1]
Documentation says opening a file while it doesn't exists will:
-do nothing in read mode
-open a new file in write mode

Current code is incorrect: pf.open(indexname, mode < 0). Mode <0 doesn't do anything. Code block should just be pf.open(indexame, mode). PF handles it correctly. I spent like an hour trying to get to the root of this wtf T_T

/*
 * Open the index file in read or write mode.
 * Under 'w' mode, the index file should be created if it does not exist.
 * @param indexname[IN] the name of the index file
 * @param mode[IN] 'r' for read, 'w' for write
 * @return error code. 0 if no error
 */
RC BTreeIndex::open(const string& indexname, char mode) //TODO: test if correct
{
	// Check if mode was valid
	if (tolower(mode) != 'r' && tolower(mode) != 'w') {
		fprintf(stderr, "Error %d: invalid file mode.\n", RC_INVALID_FILE_MODE);
		return RC_INVALID_FILE_MODE;
	}

	// If we couldn't open the file, then we make this BTreeIndex instantiation is invalid
/*	if (pf.open(indexname, mode < 0)) {
		printf("%s\n", indexname.c_str());
		rootPid = -1;
		fprintf(stderr, "Error %d: failed to open index file %s.\n", RC_FILE_OPEN_FAILED, indexname.c_str());
		return RC_FILE_OPEN_FAILED;
	}*/

**Comment by stanwayl** [comment]
"f.open(indexname, mode < 0)" should be "pf.open(indexname, mode) < 0". I think I just did a stupid. I really wanted to check if the return value of f.open() was < 0. Oops.
